### ISSUE TITLE
Add Pytorch Geometric S3DIS Dataset for Semantic Segmentation Testing

### ISSUE THREAD

**Issue by CCInc** [CCInc/3d-ml#2]
https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.S3DIS

**Comment by Stakhan** [comment]
Just to make sure I understand this one correctly:
this is just to test the training loop with `torch_geometric.datasets.s3dis` but the idea in the long run is to use `openpoints.dataset.s3dis` ?
